ruby-2-3-and-postgres-9-5-env: &ruby_2_3_and_postgres_9_5_env
  working_directory: ~/pan_domain/
  shell: /bin/bash --login
  docker:
    - image: ruby:2.3-slim
    - image: postgres:9.5-alpine
      environment:
        PGHOST: 127.0.0.1

ruby-2-3-and-postgres-9-5-14-env: &ruby_2_3_and_postgres_9_5_14_env
  working_directory: ~/pan_domain/
  shell: /bin/bash --login
  docker:
    - image: ruby:2.3-slim
    - image: postgres:9.5.14-alpine
      environment:
        PGHOST: 127.0.0.1

ruby-2-3-and-postgres-9-6-env: &ruby_2_3_and_postgres_9_6_env
  working_directory: ~/pan_domain/
  docker:
    - image: ruby:2.3-alpine
    - image: postgres:9.6-alpine
      environment:
        PGHOST: 127.0.0.1

postgres-9-6-10: &postgres_ver_9_6_10
  docker:
    - image: postgres:9.6.10-alpine

postgres-10: &postgres_ver_10
  docker:
    - image: postgres:10-alpine

postgres-10-1: &postgres_ver_10_1
  docker:
    - image: postgres:10.1-alpine

postgres-10-2: &postgres_ver_10_2
  docker:
    - image: postgres:10.2-alpine

postgres-10-3: &postgres_ver_10_3
  docker:
    - image: postgres:10.3-alpine

postgres-10-4: &postgres_ver_10_4
  docker:
    - image: postgres:10.4-alpine

postgres-10-5: &postgres_ver_10_5
  docker:
    - image: postgres:10.5-alpine

postgres-11-0: &postgres_ver_10_0
  docker:
    - image: postgres:10.0-alpine

run-bundle-install: &run_bundle_install
  name: Install Bundle dependencies
  command: bundle install

run-all-tests: &run_all_tests
  name: Run all tests
  command: rake spec


version: 2
jobs:
  ruby_2_3_and_postgres_9_5_test:
    <<: *ruby_2_3_and_postgres_9_5_env
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install git -y
      - run: apt-get install gcc -y
      - run: apt-get install make -y
      - run: apt-get install libpq-dev -y
      - run: *run_bundle_install
      - run: *run_all_tests
  
  ruby_2_3_and_postgres_9_5_14_test:
    <<: *ruby_2_3_and_postgres_9_5_14_env
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install git -y
      - run: apt-get install gcc -y
      - run: apt-get install make -y
      - run: apt-get install libpq-dev -y
      - run: *run_bundle_install
      - run: *run_all_tests

  ruby_2_3_and_postgres_9_6_test:
    <<: *ruby_2_3_and_postgres_9_6_env
    steps:
      - checkout
      - run:
          name: Install gem dependencies
          command: |
            apk add --update tzdata
            apk add git
            apk add build-base
            apk add postgresql-dev
      - run:
          name: Configure database
          command: |
            cd spec/sample_app
            echo "test:
              adapter: postgresql
              database: test_pan_domain_{{ .Environment.CIRCLE_NODE_INDEX }}
              username: postgres
              pool: 5
              host: 127.0.0.1" > config/database.yml
      - run: *run_bundle_install
      - run: *run_all_tests


workflows:
  version: 2
  ruby-2-3-and-postgres-database-tests:
    jobs:
      - ruby_2_3_and_postgres_9_5_test
      - ruby_2_3_and_postgres_9_5_14_test
      - ruby_2_3_and_postgres_9_6_test
